/// <reference lib="webworker" />
// Parsing and aggregation run here so large imports never block the UI thread.
// Only compact aggregates cross back to the page. Nothing is logged or persisted.
import { Engine } from './engine';
import type { WorkerRequest, WorkerResponse } from './protocol';

const engine = new Engine();
const post = (m: WorkerResponse) => (self as unknown as DedicatedWorkerGlobalScope).postMessage(m);

async function handle(req: WorkerRequest): Promise<unknown> {
  switch (req.type) {
    case 'import': {
      const inputs = [];
      for (const f of req.files) inputs.push({ name: f.name, bytes: new Uint8Array(await f.arrayBuffer()) });
      return engine.import(inputs, (done, total, label) => post({ type: 'progress', done, total, label }));
    }
    case 'aggregate': return engine.aggregate(req.query, req.maxTop, req.colored);
    case 'details': return engine.details(req.query, req.seriesKey, req.periodIndex);
    case 'ranks': return engine.ranks(req.query);
    case 'clock': return engine.clock(req.query, req.offsetHours, req.timeZone ?? null);
    case 'summary': return engine.summary(req.settings);
    case 'report': return engine.reportData(req.settings, req.options, req.timeZone);
    case 'whole': return engine.wholeAlbums(req.settings, req.scope ?? null);
    case 'insights': return engine.insights(req.settings, req.timeZone);
    case 'patterns': return engine.patterns(req.settings, req.k, req.tastes ?? true, req.mapSize);
    case 'search': return engine.search(req.q);
    case 'table': return engine.table(req.query, req.limit);
    case 'decades': return engine.decades(req.query, req.by);
    case 'tree': return engine.treeSummary(req.settings);
    case 'entity': return engine.entity(req.kind, req.entityId, req.settings, req.timeZone ?? null);
    case 'setGenres': return engine.setGenres(req.csv);
    case 'setEnrichment': return engine.setEnrichment(req.tree, req.artistCsv, req.albumCsv);
    case 'clearGenres': engine.clearGenres(); return null;
    case 'setArt': engine.setArt(req.index); return null;
    case 'artistList': return engine.topArtistNames(req.limit);
    case 'reset': engine.reset(); return null;
  }
}

self.onmessage = async (ev: MessageEvent<WorkerRequest>) => {
  const req = ev.data;
  try {
    post({ type: 'result', id: req.id, value: await handle(req) });
  } catch (e) {
    // Error messages are generated by our own code and never include record contents.
    post({ type: 'error', id: req.id, message: e instanceof Error ? e.message : 'Unexpected error' });
  }
};
